import React from "react";
import { 
  Sparkles, 
  BookOpen, 
  Check, 
  Copy, 
  Terminal, 
  Flame, 
  Code2, 
  LineChart,
  ChevronRight
} from "lucide-react";
import { GitHubRepo, AIRepoAnalysis } from "../types";

interface AIRepoAnalysisPanelProps {
  repo: GitHubRepo;
  repoDetails: any;
  analysis: AIRepoAnalysis | null;
  onAnalyze: () => void;
  isAnalyzing: boolean;
}

export default function AIRepoAnalysisPanel({
  repo,
  repoDetails,
  analysis,
  onAnalyze,
  isAnalyzing
}: AIRepoAnalysisPanelProps) {
  const [copied, setCopied] = React.useState(false);

  const handleCopyReadme = () => {
    if (!analysis) return;
    navigator.clipboard.writeText(analysis.enhancedReadme);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Map score rating to color coding
  const getRatingColor = (rating: string) => {
    const clean = rating.trim().toUpperCase()[0];
    if (clean === "A") return "text-emerald-400 bg-emerald-950/40 border-emerald-800/50 shadow-emerald-500/10";
    if (clean === "B") return "text-blue-400 bg-blue-950/40 border-blue-800/50 shadow-blue-500/10";
    if (clean === "C") return "text-amber-400 bg-amber-950/40 border-amber-800/50 shadow-amber-500/10";
    return "text-red-400 bg-red-950/40 border-red-800/50 shadow-red-500/10";
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-md flex flex-col gap-6" id="repo-analysis-panel">
      {/* Title Meta Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <span className="text-[10px] font-mono tracking-widest text-cyan-400 uppercase font-bold">Selected Repository</span>
          <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2 mt-0.5" id="active-repo-name">
            {repo.name}
          </h3>
          <p className="text-xs text-slate-400 max-w-lg truncate mt-0.5">{repo.description || "No description provided."}</p>
        </div>

        {!analysis && !isAnalyzing && (
          <button
            onClick={onAnalyze}
            className="py-2.5 px-5 rounded-xl font-medium text-sm bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white flex items-center gap-2 cursor-pointer transition-all shrink-0 shadow-lg shadow-cyan-500/10"
            id="btn-analyze-repo"
          >
            <Sparkles className="w-4 h-4 animate-pulse" />
            <span>Analyze Code with Gemini</span>
          </button>
        )}
      </div>

      {/* BEFORE ANALYSIS OR LOADING STATE */}
      {!analysis ? (
        <div className="flex flex-col items-center justify-center py-12 text-center" id="analysis-empty-or-loading">
          {isAnalyzing ? (
            <div className="flex flex-col items-center gap-4">
              <div className="relative flex items-center justify-center">
                <div className="w-12 h-12 rounded-full border-2 border-slate-800 border-t-cyan-500 animate-spin" />
                <Sparkles className="w-5 h-5 text-cyan-400 absolute animate-pulse" />
              </div>
              <div className="flex flex-col gap-1 max-w-sm mt-2">
                <p className="text-sm font-semibold text-slate-200">Gemini is performing a Code Review...</p>
                <p className="text-xs text-slate-500">Scanning directory structure, package dependencies, stack complexity, and current documentation quality.</p>
              </div>
            </div>
          ) : (
            <div className="flex flex-col items-center gap-3 max-w-md">
              <div className="p-3 bg-slate-950/60 border border-slate-800/80 rounded-2xl text-slate-500">
                <Terminal className="w-8 h-8 text-cyan-500/60" />
              </div>
              <h4 className="text-sm font-semibold text-slate-300">Ready for AI Engineering Review</h4>
              <p className="text-xs text-slate-500 leading-relaxed">
                Unlock code quality grades, full dependency evaluations, refactoring advice, and custom documentation improvements generated by Gemini for <strong className="text-slate-300">{repo.name}</strong>.
              </p>
            </div>
          )}
        </div>
      ) : (
        /* ANALYSIS RESULT RECEIVED */
        <div className="flex flex-col gap-6 animate-fadeIn" id="analysis-result">
          {/* Top Row: Overall Score Billboard & Numeric Bars */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            {/* Billboard score */}
            <div className={`border rounded-2xl p-5 flex flex-col items-center justify-center gap-2 text-center shadow-lg ${getRatingColor(analysis.rating)}`}>
              <span className="text-[10px] uppercase font-mono tracking-wider font-bold opacity-80">Project Grade</span>
              <span className="text-5xl font-extrabold font-mono tracking-tight glow-cyan-sm">
                {analysis.rating}
              </span>
              <span className="text-xs mt-1 font-medium font-sans">Engineering Rating</span>
            </div>

            {/* Quality & Documentation Bars */}
            <div className="md:col-span-2 bg-slate-950/30 border border-slate-800/60 rounded-2xl p-5 flex flex-col justify-center gap-4">
              {/* Code Quality Bar */}
              <div className="flex flex-col gap-1.5">
                <div className="flex justify-between text-xs">
                  <span className="font-semibold text-slate-300 flex items-center gap-1.5">
                    <Code2 className="w-4 h-4 text-cyan-400" />
                    <span>Code Quality / Structure</span>
                  </span>
                  <span className="font-mono text-cyan-400 font-bold">{analysis.codeQualityRating} / 10</span>
                </div>
                <div className="w-full h-2 bg-slate-900 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-cyan-500 rounded-full transition-all duration-1000"
                    style={{ width: `${analysis.codeQualityRating * 10}%` }}
                  />
                </div>
              </div>

              {/* Documentation Bar */}
              <div className="flex flex-col gap-1.5">
                <div className="flex justify-between text-xs">
                  <span className="font-semibold text-slate-300 flex items-center gap-1.5">
                    <BookOpen className="w-4 h-4 text-blue-400" />
                    <span>Documentation Completeness</span>
                  </span>
                  <span className="font-mono text-blue-400 font-bold">{analysis.documentationRating} / 10</span>
                </div>
                <div className="w-full h-2 bg-slate-900 rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-blue-500 rounded-full transition-all duration-1000"
                    style={{ width: `${analysis.documentationRating * 10}%` }}
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Core Overview */}
          <div className="bg-slate-950/40 p-4 rounded-xl border border-slate-800/50 flex flex-col gap-1.5">
            <span className="text-[10px] font-mono tracking-wider font-bold text-cyan-400 uppercase">Project Overview</span>
            <p className="text-sm text-slate-200 leading-relaxed">
              {analysis.overview}
            </p>
          </div>

          {/* Architecture Critiques */}
          <div className="bg-slate-950/40 p-4 rounded-xl border border-slate-800/50 flex flex-col gap-2">
            <span className="text-[10px] font-mono tracking-wider font-bold text-cyan-400 uppercase flex items-center gap-1.5">
              <LineChart className="w-3.5 h-3.5" />
              <span>Architecture & Dependency Review</span>
            </span>
            <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line font-sans">
              {analysis.architectureReview}
            </p>
          </div>

          {/* Engineering Suggestions */}
          <div className="flex flex-col gap-3">
            <h4 className="text-sm font-semibold text-slate-300 flex items-center gap-2">
              <Flame className="w-4 h-4 text-amber-500" />
              <span>AI Refactoring & Optimization Tips</span>
            </h4>
            <div className="flex flex-col gap-2.5">
              {analysis.suggestions.map((suggestion, index) => (
                <div key={index} className="flex items-start gap-3 text-xs text-slate-300 bg-slate-950/20 border border-slate-800/40 p-3 rounded-xl hover:border-slate-800 transition-colors">
                  <ChevronRight className="w-4 h-4 text-cyan-500 shrink-0 mt-0.5" />
                  <span className="leading-relaxed">{suggestion}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Enhanced Copyable README */}
          <div className="flex flex-col gap-3 border-t border-slate-800 pt-5">
            <div className="flex items-center justify-between">
              <h4 className="text-sm font-semibold text-slate-300 flex items-center gap-2">
                <BookOpen className="w-4 h-4 text-cyan-400" />
                <span>AI-Generated High-Converting README.md</span>
              </h4>
              <button
                onClick={handleCopyReadme}
                className="py-1.5 px-3 rounded-lg text-xs font-medium bg-slate-950 border border-slate-800 hover:border-slate-700 hover:bg-slate-900 text-cyan-400 flex items-center gap-1.5 transition-all cursor-pointer"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    <span className="text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy README Markdown</span>
                  </>
                )}
              </button>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Use this professional README template specifically optimized to market your software projects, with appropriate badges, tech stack highlights, installation guidelines, and directory maps.
            </p>

            <div className="bg-slate-950 border border-slate-850 rounded-xl p-4 max-h-72 overflow-y-auto">
              <pre className="text-xs text-slate-300 font-mono whitespace-pre-wrap select-all">
                {analysis.enhancedReadme}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
